# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12wdBijesoPGjO0a2P7lBQLXkWK4IzuCG
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('/content/retail_sales_dataset.csv')

df

df.info()

df.shape

df = df.dropna(how='all')

df = df.dropna(axis=1, how='all')

print("\nDataFrame after removing blank rows and columns:")
print(df)

a=sns.countplot(data=df,x='Gender')
for bars in a.containers:
  a.bar_label(bars)

df

a=df.groupby(['Product Category','Gender'],as_index=False) ['Total Amount'].sum().sort_values(by='Total Amount',ascending=False)
sns.barplot(data=a,x='Product Category',y='Total Amount',hue='Gender')

df.describe()

a=df.groupby(['Quantity','Age'],as_index=False) ['Price'].sum().sort_values(by='Price',ascending=False)
sns.barplot(data=a,x='Quantity',y='Price',hue='Age')



